version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: moto
    versions:
    - 1.3.16
    - 2.0.0
    - 2.0.1
    - 2.0.2
    - 2.0.3
    - 2.0.4
  - dependency-name: pyzmq
    versions:
    - 21.0.2
    - 22.0.0
    - 22.0.2
  - dependency-name: python-daemon
    versions:
    - 2.2.4
